---
- name: Update apt packages.
  become: yes
  apt:
    update_cache: yes
- name: Remove dependencies that are no longer required.
  become: yes
  apt:
    autoremove: "yes"
- name: Install dependencies
  become: yes
  apt:
    name: ["nodejs", "npm", "python3", "tar", "gzip", "git"]
    state: latest
    update_cache: yes
- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
- name: set environment variables
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: udapeople-prod.cgmijslxr7aa.us-east-1.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: udapeople123
    TYPEORM_DATABASE: udapeople-prod
#- name: Create dist directory.
#  file:
#    path: "~/home/ubuntu/backend"
#    state: directory
