---
- name: move files to backend
  copy:
    src: /home/backend.tar.gz
    dest: /home/ubuntu/backend.tar.gz

- name: "install package dependencies"
  shell: |
    cd /home/ubuntu/
    tar xzvf backend.tar.gz
    mv home/circleci/project/backend .
    cd backend
    npm install && npm run build
    npm audit fix && npm run build
    pm2 start npm --name backend -- start
