---
- name: copy backend files
  become: true
  copy:
    src: /root/project/backend_artifact.tar.gz
    dest: ~/home/ubuntu

- name: install dependencies
  shell: |
    cd ~/home/ubuntu
    tar -xzvf backend_artifact.tar.gz -C backend
    rm backend_artifact.tar.gz
    cd backend/
    npm install && npm run build
    npm audit fix && npm run build
    cd dist
    echo `pwd` >> test.txt
    cat test.txt
    pm2 start npm --name backend -- start
